"""
FINBRIDGE — CreditProfile Model (Part 05)
Stores calculated FT-03 Financial Trust Scores and explainable behavioral sub-scores.

Fields:
  id                          UUID primary key
  business_id                 FK → businesses.id
  cash_flow_score             Integer 0-100 (20% weight)
  stability_score             Integer 0-100 (25% weight)
  revenue_consistency_score   Integer 0-100 (15% weight)
  expense_discipline_score    Integer 0-100 (10% weight)
  repayment_capacity_score    Integer 0-100 (15% weight)
  transaction_behavior_score  Integer 0-100 (10% weight)
  fraud_risk_score            Integer 0-100 (5% weight)
  trust_score                 Integer 0-100 (weighted aggregate)
  explanation                 JSON string containing factors and metrics
  created_at / updated_at     from TimestampMixin
"""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, Index, Integer, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.business import Business


class CreditProfile(UUIDMixin, TimestampMixin, Base):
    """
    Financial Trust Profile generated by the FT-03 Alternative Credit Engine.
    Evaluates MSME financial and operational behavior deterministically.
    """

    __tablename__ = "credit_profiles"
    __table_args__ = (
        Index("idx_credit_business_created", "business_id", "created_at"),
        Index("idx_credit_trust_score", "trust_score"),
    )

    business_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Sub-scores (0-100)
    cash_flow_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    stability_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    revenue_consistency_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    expense_discipline_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    repayment_capacity_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    transaction_behavior_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    fraud_risk_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Weighted Trust Score (0-100)
    trust_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # JSON-encoded explanation: {positive_factors, negative_factors, detailed_factors, metrics}
    explanation: Mapped[str] = mapped_column(Text, nullable=False, default="{}")

    # Relationship back to Business
    business: Mapped["Business"] = relationship(
        "Business", back_populates="credit_profiles"
    )
