"""
FINBRIDGE — Loan Models (Part 06)
FT-03: Core Micro-Lending Assessment, Offers & Repayments.

Entities:
  - LoanApplication: Borrowing intent submitted by an MSME.
  - LoanOffer: Explainable prototype recommendation generated from Financial Trust Score.
  - Repayment: Scheduled repayment installments.
"""

from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING
import uuid

from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    Uuid,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.business import Business


class LoanApplication(UUIDMixin, TimestampMixin, Base):
    """
    Loan application record submitted by an authenticated MSME business.
    """

    __tablename__ = "loan_applications"
    __table_args__ = (
        Index("idx_loan_apps_business_created", "business_id", "created_at"),
    )

    business_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    requested_amount: Mapped[Decimal] = mapped_column(
        Numeric(15, 2), nullable=False
    )
    tenure_months: Mapped[int] = mapped_column(Integer, nullable=False)
    purpose: Mapped[str] = mapped_column(String(255), nullable=False)

    # "draft" | "assessed" | "offered" | "accepted" | "rejected" | "completed"
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="draft"
    )

    # Relationships
    business: Mapped["Business"] = relationship(
        "Business", back_populates="loan_applications"
    )
    offers: Mapped[list["LoanOffer"]] = relationship(
        "LoanOffer",
        back_populates="application",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class LoanOffer(UUIDMixin, TimestampMixin, Base):
    """
    Explainable prototype recommendation generated by FT-03 loan assessment engine.
    """

    __tablename__ = "loan_offers"
    __table_args__ = (
        Index("idx_loan_offers_app_created", "loan_application_id", "created_at"),
    )

    loan_application_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("loan_applications.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    recommended_min_amount: Mapped[Decimal] = mapped_column(
        Numeric(15, 2), nullable=False, default=Decimal("0.00")
    )
    recommended_max_amount: Mapped[Decimal] = mapped_column(
        Numeric(15, 2), nullable=False, default=Decimal("0.00")
    )
    estimated_emi: Mapped[Decimal] = mapped_column(
        Numeric(15, 2), nullable=False, default=Decimal("0.00")
    )
    estimated_interest: Mapped[Decimal] = mapped_column(
        Numeric(15, 2), nullable=False, default=Decimal("0.00")
    )

    # "LOW" | "MEDIUM" | "HIGH"
    risk_level: Mapped[str] = mapped_column(
        String(20), nullable=False, default="MEDIUM"
    )

    # JSON-encoded explanation: {supporting_factors, caution_factors, burden_metrics, prototype_notes}
    explanation: Mapped[str] = mapped_column(
        Text, nullable=False, default="{}"
    )

    # Relationships
    application: Mapped["LoanApplication"] = relationship(
        "LoanApplication", back_populates="offers"
    )
    repayments: Mapped[list["Repayment"]] = relationship(
        "Repayment", back_populates="offer", cascade="all, delete-orphan"
    )


class Repayment(UUIDMixin, TimestampMixin, Base):
    """
    Scheduled repayment installment for an accepted or simulated loan offer.
    """

    __tablename__ = "repayments"
    __table_args__ = (
        Index("idx_repayments_offer_due", "loan_offer_id", "due_date"),
    )

    loan_offer_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("loan_offers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    due_date: Mapped[date] = mapped_column(Date, nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)

    # "pending" | "paid" | "overdue"
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )

    paid_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationship
    offer: Mapped["LoanOffer"] = relationship(
        "LoanOffer", back_populates="repayments"
    )
