"""
FINBRIDGE — AI Financial Coach Router (Part 08)
FT-01: Contextual Financial Literacy Layer & AI Service Integration.

Routes:
  POST /api/v1/coach/ask              Ask the AI Financial Coach a question
  POST /api/v1/coach                  Direct alias for coach query
  GET  /api/v1/coach/context          Get current business structured financial context
  GET  /api/v1/coach/education        Get 7 contextual educational lesson cards
  POST /api/v1/coach/explain-fraud    Explain why a transaction was flagged
  POST /api/v1/coach/explain-scheme   Explain government scheme alignment
"""

import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.user import User
from app.schemas.coach import (
    CoachQueryRequest,
    CoachQueryResponse,
    EducationalCardsResponse,
    ExplainFraudRequest,
    ExplainFraudResponse,
    ExplainSchemeRequest,
    ExplainSchemeResponse,
    FinancialContext,
)
from app.services.ai_service import AIService
from app.services.business import BusinessService
from app.services.coach import CoachService

router = APIRouter(prefix="/coach", tags=["coach"])


async def _require_business(current_user: User, db: AsyncSession):
    biz_service = BusinessService(db)
    business = await biz_service.get_by_user_id(current_user.id)
    if business is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Business profile not found. Please complete onboarding first.",
        )
    return business


# ─────────────────────────────────────────────────────────────────────────────
# Interactive Financial Coach Query
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/ask",
    response_model=CoachQueryResponse,
    summary="Ask the AI Financial Coach",
    description=(
        "Explains actual financial data generated by our deterministic backend. "
        "The AI Coach is provided with structured business context: revenue, expenses, "
        "net cash flow, expense ratio, trust score, fraud risk, and loan metrics. "
        "Supported questions include loan affordability, score drivers, fraud flags, "
        "and financial concepts like EMI and repayment burden."
    ),
)
async def ask_financial_coach(
    body: CoachQueryRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CoachQueryResponse:
    business = await _require_business(current_user, db)
    service = CoachService(db)
    return await service.ask_coach(
        business_id=business.id,
        question=body.question,
        history=body.history,
        context_override=body.context_override,
    )


# Alias route: POST /coach as requested by prompt
@router.post(
    "",
    response_model=CoachQueryResponse,
    include_in_schema=False,
)
async def ask_financial_coach_alias(
    body: CoachQueryRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CoachQueryResponse:
    return await ask_financial_coach(body, current_user, db)


# Legacy alias route for POST /coach/chat
@router.post(
    "/chat",
    response_model=CoachQueryResponse,
    include_in_schema=False,
)
async def chat_with_coach(
    body: CoachQueryRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CoachQueryResponse:
    return await ask_financial_coach(body, current_user, db)


# ─────────────────────────────────────────────────────────────────────────────
# Context & Educational Lesson Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@router.get(
    "/context",
    response_model=FinancialContext,
    summary="Get structured financial context for current business",
)
async def get_coach_context(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> FinancialContext:
    business = await _require_business(current_user, db)
    service = CoachService(db)
    return await service.build_financial_context(business.id)


@router.get(
    "/education",
    response_model=EducationalCardsResponse,
    summary="Get 7 contextual educational financial literacy cards",
    description=(
        "Returns curated lesson cards covering Cash Flow, EMI, Interest, "
        "Repayment Burden, Revenue Consistency, Expense Management, and Transaction Risk."
    ),
)
async def get_educational_cards() -> EducationalCardsResponse:
    service = CoachService(None)  # No DB needed for static educational cards
    cards = service.get_educational_cards()
    return EducationalCardsResponse(cards=cards)


# ─────────────────────────────────────────────────────────────────────────────
# Specific Contextual Explanations
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/explain-fraud",
    response_model=ExplainFraudResponse,
    summary="Explain why a transaction was flagged",
)
async def explain_fraud(
    body: ExplainFraudRequest,
    current_user: User = Depends(get_current_user),
) -> ExplainFraudResponse:
    ai = AIService()
    explanation = ai.explain_fraud_alert(body.model_dump())
    recommendation = (
        "Verify the merchant counterparty and payment timestamp. If legitimate, "
        "continue standard operations to establish historical baseline."
    )
    return ExplainFraudResponse(
        explanation=explanation,
        recommendation=recommendation,
        risk_level=body.risk_level,
    )


@router.post(
    "/explain-scheme",
    response_model=ExplainSchemeResponse,
    summary="Explain government scheme alignment",
)
async def explain_scheme(
    body: ExplainSchemeRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> ExplainSchemeResponse:
    business = await _require_business(current_user, db)
    ai = AIService()
    summary = ai.explain_scheme(body.model_dump(), {"business_name": business.business_name})
    return ExplainSchemeResponse(
        summary=summary,
        why_it_matches=f"Aligns with your MSME operating turnover and sector requirements with a {body.match_score}% match score.",
        next_steps=[
            "Gather Udyam registration and recent GST returns",
            "Verify eligibility criteria on the official portal",
            "Submit application through an accredited lending institution",
        ],
    )
